# Generated by Django 4.2.13 on 2024-06-10 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import wfd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfuid', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('workshop_type', models.CharField(max_length=20)),
                ('date', wfd.models.PSTDateTimeField(default=django.utils.timezone.now)),
                ('in_progress', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.CheckConstraint(check=models.Q(('workshop_type__in', ['Linux', 'VIM/Regex', 'Git', 'Docker', 'Python', 'Java'])), name='valid_workshop_type'),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfd.workshop'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='attendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfd.attendant'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfd.feedbackquestion'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfd.workshop'),
        ),
    ]
